# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('channel', models.CharField(choices=[('mobile_app', 'SEVPS mobile application'), ('navigation', 'Navigation app integration'), ('vms', 'Digital road display board'), ('city_display', 'Smart city information display'), ('radio', 'Traffic control radio')], default='mobile_app', max_length=16)),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('geohash', models.CharField(blank=True, db_index=True, max_length=12)),
                ('heading_deg', models.FloatField(default=0.0)),
                ('speed_kmh', models.FloatField(default=0.0)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('channel', models.CharField(choices=[('mobile_app', 'SEVPS mobile application'), ('navigation', 'Navigation app integration'), ('vms', 'Digital road display board'), ('city_display', 'Smart city information display'), ('radio', 'Traffic control radio')], default='vms', max_length=16)),
                ('facing_deg', models.FloatField(default=0.0)),
                ('endpoint', models.URLField(blank=True, help_text='Sign controller API endpoint')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('current_message', models.CharField(blank=True, max_length=300)),
                ('message_expires_at', models.DateTimeField(blank=True, null=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_boards', to='network.roadsegment')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DriverAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('channel', models.CharField(choices=[('mobile_app', 'SEVPS mobile application'), ('navigation', 'Navigation app integration'), ('vms', 'Digital road display board'), ('city_display', 'Smart city information display'), ('radio', 'Traffic control radio')], default='mobile_app', max_length=16)),
                ('message', models.CharField(max_length=300)),
                ('instruction', models.CharField(default='Please move to the left lane', max_length=120)),
                ('eta_seconds', models.FloatField()),
                ('radius_m', models.FloatField(default=800.0)),
                ('approach_bearing_deg', models.FloatField(default=0.0)),
                ('priority_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Critical Emergency'), (2, 'Level 2 - High Emergency'), (3, 'Level 3 - Moderate Emergency'), (4, 'Level 4 - Non-Critical Transport')])),
                ('geohash', models.CharField(blank=True, db_index=True, max_length=12)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.displayboard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
