# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveralert',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_alerts', to='dispatch.emergencytrip'),
        ),
        migrations.AddIndex(
            model_name='driveralert',
            index=models.Index(fields=['trip', '-created_at'], name='alerts_driv_trip_id_042f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='driveralert',
            index=models.Index(fields=['geohash', 'expires_at'], name='alerts_driv_geohash_bd4cc3_idx'),
        ),
    ]
