# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reference', models.CharField(db_index=True, max_length=24, unique=True)),
                ('stage', models.CharField(choices=[('created', 'Created'), ('to_scene', 'En route to scene'), ('on_scene', 'On scene - patient assessment'), ('to_hospital', 'En route to hospital'), ('arrived', 'Arrived at hospital'), ('handover', 'Patient handover complete'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=16)),
                ('incident_latitude', models.FloatField(blank=True, null=True)),
                ('incident_longitude', models.FloatField(blank=True, null=True)),
                ('incident_address', models.CharField(blank=True, max_length=300)),
                ('caller_number', models.CharField(blank=True, max_length=32)),
                ('emergency_category', models.CharField(choices=[('cardiac', 'Heart Attack / Cardiac Arrest'), ('stroke', 'Stroke'), ('burn', 'Burn'), ('trauma', 'Trauma / Major Accident'), ('poisoning', 'Poisoning'), ('respiratory', 'Respiratory Distress'), ('obstetric', 'Obstetric Emergency'), ('pediatric', 'Paediatric Emergency'), ('fire_rescue', 'Fire / Rescue'), ('transfer', 'Non-critical Transfer'), ('unknown', 'Undetermined')], db_index=True, default='unknown', max_length=20)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_notes', models.TextField(blank=True)),
                ('patient_deteriorating', models.BooleanField(default=False)),
                ('condition_updated_at', models.DateTimeField(blank=True, null=True)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('hospital_was_overridden', models.BooleanField(default=False)),
                ('priority_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Critical Emergency'), (2, 'Level 2 - High Emergency'), (3, 'Level 3 - Moderate Emergency'), (4, 'Level 4 - Non-Critical Transport')], db_index=True, default=3)),
                ('siren_mode', models.CharField(choices=[('continuous', 'Continuous high-priority siren'), ('intermittent', 'Intermittent siren'), ('burst', 'Short bursts at junctions only'), ('off', 'Silent')], default='off', max_length=16)),
                ('light_pattern', models.CharField(choices=[('max', 'Maximum-intensity flashing'), ('standard', 'Standard emergency lights'), ('flashing', 'Flashing lights'), ('off', 'Lights off')], default='off', max_length=16)),
                ('allow_contraflow', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_scene_at', models.DateTimeField(blank=True, null=True)),
                ('departed_scene_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_hospital_at', models.DateTimeField(blank=True, null=True)),
                ('handover_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=200)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('distance_remaining_m', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriorityDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Critical Emergency'), (2, 'Level 2 - High Emergency'), (3, 'Level 3 - Moderate Emergency'), (4, 'Level 4 - Non-Critical Transport')])),
                ('previous_level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 - Critical Emergency'), (2, 'Level 2 - High Emergency'), (3, 'Level 3 - Moderate Emergency'), (4, 'Level 4 - Non-Critical Transport')], null=True)),
                ('siren_mode', models.CharField(choices=[('continuous', 'Continuous high-priority siren'), ('intermittent', 'Intermittent siren'), ('burst', 'Short bursts at junctions only'), ('off', 'Silent')], max_length=16)),
                ('light_pattern', models.CharField(choices=[('max', 'Maximum-intensity flashing'), ('standard', 'Standard emergency lights'), ('flashing', 'Flashing lights'), ('off', 'Lights off')], max_length=16)),
                ('grants_green_corridor', models.BooleanField(default=False)),
                ('trigger', models.CharField(max_length=200)),
                ('rationale', models.CharField(blank=True, max_length=400)),
                ('issued_by', models.CharField(default='sevps-layer6', max_length=60)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('algorithm', models.CharField(default='astar', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('geometry', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('node_ids', models.JSONField(blank=True, default=list)),
                ('total_distance_m', models.FloatField(default=0.0)),
                ('total_duration_s', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('predicted_eta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalPreemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('planned', 'Planned'), ('armed', 'Armed - clearance running'), ('active', 'Active - corridor green'), ('released', 'Released - normal timing restored'), ('cancelled', 'Cancelled'), ('failed', 'Failed / controller unreachable')], db_index=True, default='planned', max_length=12)),
                ('planned_green_at', models.DateTimeField()),
                ('planned_release_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('predicted_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_at', models.DateTimeField(blank=True, null=True)),
                ('clearance_s', models.FloatField(default=8.0)),
                ('hold_duration_s', models.FloatField(default=20.0)),
                ('priority_score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('controller_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['planned_green_at'],
            },
        ),
    ]
