# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('fleet', '0001_initial'),
        ('hospitals', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytrip',
            name='destination_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_trips', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='emergencytrip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.emergencyvehicle'),
        ),
        migrations.AddField(
            model_name='prioritydirective',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='dispatch.emergencytrip'),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='dispatch.emergencytrip'),
        ),
        migrations.AddField(
            model_name='signalpreemption',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preemptions', to='network.trafficsignal'),
        ),
        migrations.AddField(
            model_name='signalpreemption',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preemptions', to='dispatch.emergencytrip'),
        ),
        migrations.AddField(
            model_name='signalpreemption',
            name='yielded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yielders', to='dispatch.signalpreemption'),
        ),
        migrations.AddIndex(
            model_name='emergencytrip',
            index=models.Index(fields=['stage', '-created_at'], name='dispatch_em_stage_d0c758_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencytrip',
            index=models.Index(fields=['destination_hospital', 'stage'], name='dispatch_em_destina_8ebd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='routeplan',
            index=models.Index(fields=['trip', 'is_active'], name='dispatch_ro_trip_id_b026b7_idx'),
        ),
        migrations.AddIndex(
            model_name='signalpreemption',
            index=models.Index(fields=['state', 'planned_green_at'], name='dispatch_si_state_218e06_idx'),
        ),
        migrations.AddIndex(
            model_name='signalpreemption',
            index=models.Index(fields=['trip', 'state'], name='dispatch_si_trip_id_69d9cf_idx'),
        ),
    ]
