# Generated by Django 5.0.9 on 2026-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytrip',
            name='hospital_choice_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='emergencytrip',
            name='hospital_choice_reason',
            field=models.CharField(choices=[('recommended', 'Followed the recommendation'), ('patient_request', "Patient's choice of hospital"), ('family_request', "Family's request"), ('clinical_judgement', 'Crew clinical judgement'), ('capacity', 'Capacity or diversion'), ('continuity', 'Patient already under care there')], default='recommended', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencytrip',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
