# Generated by Django 5.0.9 on 2026-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_emergencytrip_hospital_choice_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencytrip',
            name='admitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
