# Generated by Django 5.0.9 on 2026-08-03 10:24

import apps.core.profiles
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_postgis_spatial_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('qualification', models.CharField(blank=True, max_length=120)),
                ('base_station', models.CharField(blank=True, max_length=140)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('emergency_contact', models.CharField(blank=True, max_length=140)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.core.profiles.avatar_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
