# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('osm_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(db_index=True, default='Chennai', max_length=80)),
                ('is_signalised', models.BooleanField(db_index=True, default=False)),
                ('base_delay_s', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['name', 'id'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='network_int_latitud_088145_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('road_class', models.CharField(choices=[('motorway', 'Motorway'), ('trunk', 'Trunk'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('residential', 'Residential'), ('service', 'Service road')], db_index=True, default='secondary', max_length=20)),
                ('length_m', models.FloatField()),
                ('lanes', models.PositiveSmallIntegerField(default=2)),
                ('free_flow_kmh', models.FloatField(default=40.0)),
                ('geometry', models.JSONField(blank=True, default=list)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('allows_contraflow', models.BooleanField(default=False)),
                ('current_speed_kmh', models.FloatField(blank=True, null=True)),
                ('congestion_level', models.CharField(choices=[('free', 'Free flow'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('jam', 'Standstill')], db_index=True, default='free', max_length=12)),
                ('speed_updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('congestion_index', models.FloatField(default=0.0)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='network.intersection')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='network.intersection')),
            ],
        ),
        migrations.CreateModel(
            name='RoadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('event_type', models.CharField(choices=[('accident', 'Accident'), ('closure', 'Road closure'), ('construction', 'Construction'), ('congestion', 'Heavy congestion'), ('public_event', 'Public gathering / event'), ('waterlogging', 'Waterlogging'), ('illegal_parking', 'Illegal parking'), ('lane_obstruction', 'Lane obstruction'), ('blockage', 'Road blockage')], db_index=True, max_length=20)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('severity', models.FloatField(default=0.5)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(choices=[('cv', 'Computer vision'), ('operator', 'Traffic operator'), ('crowd', 'Crowdsourced report'), ('provider', 'External traffic provider'), ('predicted', 'AI prediction'), ('simulation', 'Simulation')], default='operator', max_length=16)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('radius_m', models.FloatField(default=120.0)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='network.roadsegment')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('stream_url', models.CharField(blank=True, max_length=500)),
                ('heading_deg', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_analysed_at', models.DateTimeField(blank=True, null=True)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='network.intersection')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='network.roadsegment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('speed_kmh', models.FloatField()),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('density', models.FloatField(default=0.0)),
                ('occupancy', models.FloatField(default=0.0, help_text='Fraction of frame covered by vehicles')),
                ('congestion_level', models.CharField(choices=[('free', 'Free flow'), ('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('jam', 'Standstill')], default='free', max_length=12)),
                ('source', models.CharField(choices=[('cv', 'Computer vision'), ('operator', 'Traffic operator'), ('crowd', 'Crowdsourced report'), ('provider', 'External traffic provider'), ('predicted', 'AI prediction'), ('simulation', 'Simulation')], default='simulation', max_length=16)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='network.camerafeed')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='network.roadsegment')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Monday .. 6=Sunday')),
                ('hour', models.PositiveSmallIntegerField()),
                ('speed_factor', models.FloatField(default=1.0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='network.roadsegment')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('controller_id', models.CharField(max_length=64, unique=True)),
                ('controller_type', models.CharField(default='simulated', max_length=32)),
                ('endpoint', models.URLField(blank=True)),
                ('cycle_seconds', models.PositiveIntegerField(default=120)),
                ('phase_plan', models.JSONField(blank=True, default=dict)),
                ('supports_preemption', models.BooleanField(default=True)),
                ('min_recovery_s', models.PositiveIntegerField(default=45)),
                ('current_phase', models.CharField(choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green'), ('flashing_amber', 'Flashing amber'), ('off', 'Dark / manual control')], default='red', max_length=16)),
                ('is_preempted', models.BooleanField(db_index=True, default=False)),
                ('preempted_until', models.DateTimeField(blank=True, null=True)),
                ('last_preempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('is_online', models.BooleanField(db_index=True, default=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='network.intersection')),
            ],
            options={
                'ordering': ['controller_id'],
            },
        ),
        migrations.CreateModel(
            name='AccidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('severity', models.PositiveSmallIntegerField(default=2, help_text='1=minor, 2=serious, 3=fatal')),
                ('casualties', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accidents', to='network.intersection')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='network_acc_latitud_7890e9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='roadsegment',
            index=models.Index(fields=['from_node', 'to_node'], name='network_roa_from_no_b4f5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='roadsegment',
            index=models.Index(fields=['is_open', 'congestion_level'], name='network_roa_is_open_4ce063_idx'),
        ),
        migrations.AddConstraint(
            model_name='roadsegment',
            constraint=models.UniqueConstraint(fields=('from_node', 'to_node'), name='uniq_directed_segment'),
        ),
        migrations.AddConstraint(
            model_name='roadsegment',
            constraint=models.CheckConstraint(check=models.Q(('length_m__gt', 0)), name='segment_length_positive'),
        ),
        migrations.AddIndex(
            model_name='roadevent',
            index=models.Index(fields=['is_active', 'event_type'], name='network_roa_is_acti_5d0758_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficobservation',
            index=models.Index(fields=['segment', '-observed_at'], name='network_tra_segment_ce553e_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficobservation',
            index=models.Index(fields=['-observed_at'], name='network_tra_observe_9a9969_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficprofile',
            index=models.Index(fields=['segment', 'weekday', 'hour'], name='network_tra_segment_b5d0cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='trafficprofile',
            constraint=models.UniqueConstraint(fields=('segment', 'weekday', 'hour'), name='uniq_profile_cell'),
        ),
    ]
