# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('city', models.CharField(db_index=True, default='Chennai', max_length=80)),
                ('trips_total', models.PositiveIntegerField(default=0)),
                ('trips_completed', models.PositiveIntegerField(default=0)),
                ('trips_cancelled', models.PositiveIntegerField(default=0)),
                ('avg_response_time_s', models.FloatField(blank=True, null=True)),
                ('median_response_time_s', models.FloatField(blank=True, null=True)),
                ('p90_response_time_s', models.FloatField(blank=True, null=True)),
                ('avg_transport_time_s', models.FloatField(blank=True, null=True)),
                ('green_corridors_created', models.PositiveIntegerField(default=0)),
                ('signals_preempted', models.PositiveIntegerField(default=0)),
                ('total_hold_seconds', models.FloatField(default=0.0)),
                ('avg_eta_error_s', models.FloatField(blank=True, null=True)),
                ('reroutes', models.PositiveIntegerField(default=0)),
                ('driver_alerts_issued', models.PositiveIntegerField(default=0)),
                ('hospital_overrides', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('kind', models.CharField(choices=[('accident', 'Accident-prone location'), ('congestion', 'Recurring congestion'), ('delay', 'High-delay intersection')], db_index=True, max_length=12)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('incident_count', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('window_days', models.PositiveIntegerField(default=180)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailymetric',
            constraint=models.UniqueConstraint(fields=('date', 'city'), name='uniq_daily_metric'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='intersection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspots', to='network.intersection'),
        ),
        migrations.AddIndex(
            model_name='hotspot',
            index=models.Index(fields=['kind', '-score'], name='analytics_h_kind_7189ac_idx'),
        ),
    ]
