# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('city', models.CharField(default='Chennai', max_length=80)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('contact_number', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('callsign', models.CharField(db_index=True, max_length=32, unique=True)),
                ('registration', models.CharField(blank=True, max_length=24)),
                ('vehicle_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('fire_engine', 'Fire Engine'), ('police', 'Police Vehicle'), ('disaster', 'Disaster Response Unit')], db_index=True, default='ambulance', max_length=20)),
                ('operator', models.CharField(blank=True, help_text='Operating agency', max_length=140)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('available', 'Available'), ('dispatched', 'Dispatched - en route to scene'), ('on_scene', 'On scene'), ('transporting', 'Transporting patient'), ('at_hospital', 'At hospital - handover'), ('returning', 'Returning to base'), ('out_of_service', 'Out of service')], db_index=True, default='offline', max_length=20)),
                ('latitude', models.FloatField(db_index=True, default=0.0)),
                ('longitude', models.FloatField(db_index=True, default=0.0)),
                ('heading_deg', models.FloatField(default=0.0)),
                ('speed_kmh', models.FloatField(default=0.0)),
                ('accuracy_m', models.FloatField(default=10.0)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Critical Emergency'), (2, 'Level 2 - High Emergency'), (3, 'Level 3 - Moderate Emergency'), (4, 'Level 4 - Non-Critical Transport')], default=4)),
                ('siren_mode', models.CharField(choices=[('continuous', 'Continuous high-priority siren'), ('intermittent', 'Intermittent siren'), ('burst', 'Short bursts at junctions only'), ('off', 'Silent')], default='off', max_length=16)),
                ('light_pattern', models.CharField(choices=[('max', 'Maximum-intensity flashing'), ('standard', 'Standard emergency lights'), ('flashing', 'Flashing lights'), ('off', 'Lights off')], default='off', max_length=16)),
                ('is_als', models.BooleanField(default=False, verbose_name='Advanced Life Support')),
                ('crew_size', models.PositiveSmallIntegerField(default=2)),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('device_token', models.CharField(blank=True, help_text='Push notification token', max_length=255)),
                ('home_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet.station')),
            ],
            options={
                'ordering': ['callsign'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0.0)),
                ('heading_deg', models.FloatField(default=0.0)),
                ('accuracy_m', models.FloatField(default=10.0)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry', to='dispatch.emergencytrip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='fleet.emergencyvehicle')),
            ],
            options={
                'verbose_name_plural': 'vehicle telemetry',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencyvehicle',
            index=models.Index(fields=['status', 'vehicle_type'], name='fleet_emerg_status_e91730_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyvehicle',
            index=models.Index(fields=['latitude', 'longitude'], name='fleet_emerg_latitud_84a5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletelemetry',
            index=models.Index(fields=['vehicle', '-recorded_at'], name='fleet_vehic_vehicle_e39860_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicletelemetry',
            index=models.Index(fields=['trip', 'recorded_at'], name='fleet_vehic_trip_id_20b10e_idx'),
        ),
    ]
