# Generated by Django 5.0.9 on 2026-08-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvehicle',
            name='ownership',
            field=models.CharField(choices=[('government', 'Government'), ('private_hospital', 'Private Hospital'), ('private_service', 'Private Ambulance Service'), ('ngo', 'NGO / Charitable Trust')], db_index=True, default='government', help_text='Operating sector - decides billing, escalation contact and dispatch agreement', max_length=20),
        ),
    ]
