# Generated by Django 5.0.9 on 2026-08-03 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_retire_fire_and_police_vehicles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting paramedic acceptance'), ('active', 'Active - crew on duty'), ('declined', 'Declined by paramedic'), ('ended', 'Ended')], db_index=True, default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.CharField(blank=True, max_length=300)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driving_shifts', to=settings.AUTH_USER_MODEL)),
                ('paramedic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attending_shifts', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.emergencyvehicle')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, max_length=300)),
                ('skipped_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_checks', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_check', to='fleet.crewshift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crewshift',
            index=models.Index(fields=['vehicle', 'status'], name='fleet_crews_vehicle_7c6822_idx'),
        ),
        migrations.AddIndex(
            model_name='crewshift',
            index=models.Index(fields=['status', '-requested_at'], name='fleet_crews_status_d3078f_idx'),
        ),
        migrations.AddConstraint(
            model_name='crewshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('vehicle',), name='one_open_shift_per_vehicle'),
        ),
    ]
