# Generated by Django 5.0.9 on 2026-08-03 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_emergencytrip_hospital_choice_note_and_more'),
        ('fleet', '0004_crewshift_equipmentcheck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvehicle',
            name='readiness',
            field=models.CharField(choices=[('unchecked', 'Not yet inspected'), ('ready', 'Ready for service'), ('temporarily_ready', 'Temporarily ready - inspection pending'), ('not_ready', 'Not ready - failed inspection'), ('maintenance', 'In maintenance')], db_index=True, default='unchecked', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencyvehicle',
            name='readiness_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BreakdownEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(choices=[('open', 'Open - seeking replacement'), ('transfer_accepted', 'Replacement accepted'), ('transfer_complete', 'Patient transferred'), ('resolved', 'Resolved without transfer'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('replacement_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_rescues', to='fleet.emergencyvehicle')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdowns', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='dispatch.emergencytrip')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='fleet.emergencyvehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('failed_items', models.JSONField(blank=True, default=list)),
                ('remarks', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('open', 'Open - awaiting workshop'), ('acknowledged', 'Acknowledged by fleet'), ('in_progress', 'Repair in progress'), ('resolved', 'Resolved - vehicle returned to service')], db_index=True, default='open', max_length=16)),
                ('from_inspection', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_maintenance', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reports', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_reports', to='fleet.crewshift')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reports', to='fleet.emergencyvehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_m', models.FloatField(default=0.0)),
                ('state', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn - another crew took it')], db_index=True, default='offered', max_length=12)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=200)),
                ('breakdown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='fleet.breakdownevent')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_responses', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_offers', to='fleet.emergencyvehicle')),
            ],
            options={
                'ordering': ['distance_m'],
            },
        ),
        migrations.AddIndex(
            model_name='breakdownevent',
            index=models.Index(fields=['state', '-created_at'], name='fleet_break_state_9fe3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownevent',
            index=models.Index(fields=['trip', '-created_at'], name='fleet_break_trip_id_7f3a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['vehicle', '-created_at'], name='fleet_maint_vehicle_568cad_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancereport',
            index=models.Index(fields=['state', '-created_at'], name='fleet_maint_state_f89fb9_idx'),
        ),
        migrations.AddConstraint(
            model_name='transferoffer',
            constraint=models.UniqueConstraint(fields=('breakdown', 'vehicle'), name='one_offer_per_vehicle_per_breakdown'),
        ),
    ]
