# Generated by Django 5.0.9 on 2026-08-03 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_emergencyvehicle_readiness_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crewshift',
            name='one_open_shift_per_vehicle',
        ),
        migrations.AlterField(
            model_name='crewshift',
            name='paramedic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attending_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crewshift',
            name='status',
            field=models.CharField(choices=[('draft', 'Vehicle claimed - inspection in progress'), ('pending', 'Awaiting paramedic acceptance'), ('active', 'Active - crew on duty'), ('declined', 'Declined by paramedic'), ('ended', 'Ended')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='crewshift',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'active'])), fields=('vehicle',), name='one_open_shift_per_vehicle'),
        ),
    ]
