# Generated by Django 5.0.9 on 2026-08-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_crewshift_one_open_shift_per_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyvehicle',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Always on a synthetic response. Cannot be taken over by a driver.', verbose_name='Demonstration unit'),
        ),
    ]
