# Generated by Django 5.0.9 on 2026-08-02 12:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('cardiac', 'Heart Attack / Cardiac Arrest'), ('stroke', 'Stroke'), ('burn', 'Burn'), ('trauma', 'Trauma / Major Accident'), ('poisoning', 'Poisoning'), ('respiratory', 'Respiratory Distress'), ('obstetric', 'Obstetric Emergency'), ('pediatric', 'Paediatric Emergency'), ('fire_rescue', 'Fire / Rescue'), ('transfer', 'Non-critical Transfer'), ('unknown', 'Undetermined')], db_index=True, max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('required_facilities', models.JSONField(default=list, help_text='List of HospitalFacility codes - all are mandatory')),
                ('preferred_facilities', models.JSONField(blank=True, default=list)),
                ('default_priority_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Critical Emergency'), (2, 'Level 2 - High Emergency'), (3, 'Level 3 - Moderate Emergency'), (4, 'Level 4 - Non-Critical Transport')], default=2)),
                ('requires_icu', models.BooleanField(default=False)),
                ('golden_window_min', models.PositiveIntegerField(blank=True, null=True)),
                ('time_critical', models.BooleanField(default=False)),
                ('guidance', models.TextField(blank=True, help_text='Pre-arrival instructions for the crew')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('city', models.CharField(db_index=True, default='Chennai', max_length=80)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('emergency_phone', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_trauma_designated', models.BooleanField(default=False)),
                ('quality_index', models.FloatField(default=0.7)),
                ('is_on_diversion', models.BooleanField(db_index=True, default=False)),
                ('diversion_reason', models.CharField(blank=True, max_length=200)),
                ('staff_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='auth.group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('emergency_category', models.CharField(choices=[('cardiac', 'Heart Attack / Cardiac Arrest'), ('stroke', 'Stroke'), ('burn', 'Burn'), ('trauma', 'Trauma / Major Accident'), ('poisoning', 'Poisoning'), ('respiratory', 'Respiratory Distress'), ('obstetric', 'Obstetric Emergency'), ('pediatric', 'Paediatric Emergency'), ('fire_rescue', 'Fire / Rescue'), ('transfer', 'Non-critical Transfer'), ('unknown', 'Undetermined')], max_length=20)),
                ('priority_level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 - Critical Emergency'), (2, 'Level 2 - High Emergency'), (3, 'Level 3 - Moderate Emergency'), (4, 'Level 4 - Non-Critical Transport')])),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('distance_remaining_m', models.FloatField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.CharField(blank=True, max_length=120)),
                ('preparation_notes', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='hospitals.hospital')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_alerts', to='dispatch.emergencytrip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HospitalCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.CharField(choices=[('cardiac_icu', 'Cardiac ICU'), ('cath_lab', 'Catheterisation Lab'), ('neurology', 'Neurology'), ('ct_scan', 'CT Scan'), ('mri', 'MRI'), ('burn_unit', 'Burn Unit'), ('trauma_center', 'Trauma Center'), ('toxicology', 'Toxicology'), ('icu', 'General ICU'), ('operation_theatre', 'Operation Theatre'), ('blood_bank', 'Blood Bank'), ('ventilator', 'Ventilator support'), ('dialysis', 'Dialysis'), ('nicu', 'Neonatal ICU'), ('picu', 'Paediatric ICU'), ('obstetrics', 'Obstetrics / Labour ward'), ('stroke_unit', 'Stroke Unit'), ('emergency_dept', 'Emergency Department')], db_index=True, max_length=32)),
                ('is_available', models.BooleanField(default=True)),
                ('unavailable_reason', models.CharField(blank=True, max_length=200)),
                ('units', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='hospitals.hospital')),
            ],
            options={
                'verbose_name_plural': 'hospital capabilities',
                'ordering': ['hospital', 'facility'],
            },
        ),
        migrations.CreateModel(
            name='HospitalCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_beds_total', models.PositiveIntegerField(default=20)),
                ('emergency_beds_available', models.PositiveIntegerField(default=10)),
                ('icu_beds_total', models.PositiveIntegerField(default=10)),
                ('icu_beds_available', models.PositiveIntegerField(default=4)),
                ('ventilators_available', models.PositiveIntegerField(default=2)),
                ('operation_theatres_free', models.PositiveIntegerField(default=1)),
                ('patients_waiting', models.PositiveIntegerField(default=0)),
                ('doctors_on_duty', models.PositiveSmallIntegerField(default=3)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_row', to='hospitals.hospital')),
            ],
            options={
                'verbose_name_plural': 'hospital capacity',
            },
        ),
        migrations.CreateModel(
            name='HospitalRecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_category', models.CharField(choices=[('cardiac', 'Heart Attack / Cardiac Arrest'), ('stroke', 'Stroke'), ('burn', 'Burn'), ('trauma', 'Trauma / Major Accident'), ('poisoning', 'Poisoning'), ('respiratory', 'Respiratory Distress'), ('obstetric', 'Obstetric Emergency'), ('pediatric', 'Paediatric Emergency'), ('fire_rescue', 'Fire / Rescue'), ('transfer', 'Non-critical Transfer'), ('unknown', 'Undetermined')], max_length=20)),
                ('override_reason', models.CharField(blank=True, max_length=300)),
                ('candidates', models.JSONField(default=list)),
                ('rule_snapshot', models.JSONField(default=dict)),
                ('chosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for', to='hospitals.hospital')),
                ('recommended', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='hospitals.hospital')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='dispatch.emergencytrip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city', 'is_active'], name='hospitals_h_city_89f9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitalalert',
            index=models.Index(fields=['hospital', '-created_at'], name='hospitals_h_hospita_357c58_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitalcapability',
            constraint=models.UniqueConstraint(fields=('hospital', 'facility'), name='uniq_hospital_facility'),
        ),
    ]
