# Generated by Django 5.0.9 on 2026-08-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalalert',
            name='symptoms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
