# Generated by Django 5.0.9 on 2026-08-03 17:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospitalalert_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalcapacity',
            name='burn_unit_beds_available',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='burn_unit_beds_total',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='cardiac_icu_available',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='cardiac_icu_total',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='emergency_cases_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='emergency_staff_on_duty',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='general_beds_available',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='general_beds_total',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='operation_theatres_total',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='pediatric_beds_available',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='pediatric_beds_total',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='hospitalcapacity',
            name='ventilators_total',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.CreateModel(
            name='HospitalTeamReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emergency_team_ready', models.BooleanField(default=True)),
                ('trauma_team_ready', models.BooleanField(default=True)),
                ('cardiology_ready', models.BooleanField(default=True)),
                ('neurology_ready', models.BooleanField(default=False)),
                ('burn_unit_ready', models.BooleanField(default=False)),
                ('icu_ready', models.BooleanField(default=True)),
                ('operation_theatre_ready', models.BooleanField(default=True)),
                ('blood_bank_ready', models.BooleanField(default=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_readiness', to='hospitals.hospital')),
            ],
            options={
                'verbose_name_plural': 'hospital team readiness',
            },
        ),
    ]
