# Generated by Django 5.0.9 on 2026-08-02 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_initial'),
        ('dispatch', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muted_categories', models.JSONField(blank=True, default=list)),
                ('quiet_hours_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quiet_hours_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('severity', models.CharField(db_index=True, default='info', max_length=16)),
                ('category', models.CharField(choices=[('inbound_patient', 'Inbound patient'), ('corridor', 'Green corridor / signal preemption'), ('priority', 'Priority escalation'), ('route', 'Route change'), ('dispatch', 'Dispatch and assignment'), ('road_hazard', 'Road hazard and closure'), ('fleet', 'Fleet health'), ('system', 'Platform and system')], db_index=True, default='system', max_length=32)),
                ('audience', models.JSONField(blank=True, default=list)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='dispatch.emergencytrip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend', models.CharField(choices=[('webpush', 'Web Push (VAPID)'), ('fcm', 'Firebase Cloud Messaging')], default='webpush', max_length=16)),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(blank=True, max_length=255)),
                ('auth', models.CharField(blank=True, max_length=255)),
                ('geohash', models.CharField(blank=True, db_index=True, max_length=12)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_reason', models.CharField(blank=True, max_length=200)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_subscriptions', to='alerts.driverdevice')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous road-user devices subscribed to driver alerts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Accepted by push service'), ('failed', 'Failed'), ('expired', 'Subscription gone'), ('skipped', 'Suppressed by preference')], db_index=True, default='pending', max_length=12)),
                ('backend', models.CharField(choices=[('webpush', 'Web Push (VAPID)'), ('fcm', 'Firebase Cloud Messaging')], max_length=16)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=250)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notify.notificationrecord')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notify.pushsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notificationrecord',
            index=models.Index(fields=['-created_at', 'severity'], name='notify_noti_created_65d276_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecord',
            index=models.Index(fields=['dedupe_key', '-created_at'], name='notify_noti_dedupe__7e00cf_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationrecord',
            index=models.Index(fields=['category', '-created_at'], name='notify_noti_categor_2aabcb_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['is_active', 'backend'], name='notify_push_is_acti_4d5dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='notify_push_user_id_1bcd4f_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'state'], name='notify_noti_notific_998ec6_idx'),
        ),
    ]
